
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = sns.load_dataset('titanic')

print("First 5 rows:", df.head())
print("Info:")
print(df.info())
print("Summary statistics:", df.describe(include='all'))
print("Missing values:", df.isnull().sum())
plt.figure(figsize=(8, 5))
sns.histplot(df['age'].dropna(), kde=True)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()
plt.figure(figsize=(6, 4))
sns.countplot(x='survived', data=df)
plt.title("Survival Count (0 = No, 1 = Yes)")
plt.show()
plt.figure(figsize=(6, 4))
sns.countplot(x='sex', hue='survived', data=df)
plt.title("Survival by Gender")
plt.show()
plt.figure(figsize=(6, 4))
sns.countplot(x='pclass', hue='survived', data=df)
plt.title("Survival by Passenger Class")
plt.show()
plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()
plt.figure(figsize=(8, 5))
sns.boxplot(x='sex', y='age', data=df)
plt.title("Age Distribution by Gender")
plt.show()
grouped = df.groupby(['class', 'sex'])['survived'].mean().reset_index()
print("Survival Rate by Class and Gender:", grouped)
